eMart/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eMart.Models
{
    public class Category
    {

        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Name")]
        public string? Name { get; set; }

      
        public byte[] ?Image { get; set; }

        public List<SubCategory>? SubCategories { get; set; }

        [NotMapped]
        public IFormFile? ClientFile { get; set; }


        [NotMapped]
        public string? ImgSrc
        {
            get
            {
                if (Image != null)
                {
                    string base64String = Convert.ToBase64String(Image, 0, Image.Length);
                    return "data:image/jpg;base64," + base64String;
                }
                else
                {
                    return string.Empty;
                }
            }
        }

    }
}

eMart/Areas/Admin/Controllers/CategoryController.cs
using eMart.Models;
using eMart.Repository.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Runtime.InteropServices;

namespace eMart.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = clsRoles.RoleAdmin)]
    public class CategoryController : Controller
    {

        public CategoryController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        private readonly IUnitOfWork _unit;

        public async Task<IActionResult> Index()
        {
            ViewBag.isAdmin = HttpContext.Session.GetString("isAdmin");
            ViewData["Count"] = HttpContext.Session.GetInt32("count");
            var categories = await _unit.categories.FindAllAsync(nameof(Category.SubCategories));
            return View(categories);
        }

        public IActionResult InsertorEdit(int? id)
        {
            ViewBag.isAdmin = HttpContext.Session.GetString("isAdmin");
            ViewData["Count"] = HttpContext.Session.GetInt32("count");
            if (id == 0 || id == null)
            {

                return View();
            }
            
            var i = _unit.categories.Find((int)id);
        
            if (i == null)
            {
                return BadRequest();
            }
            else
            {

                return View(i);
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult InsertorEdit(Category t)
        {
          
            if (t.Name.Contains("0") || t.Name.Contains("1") || t.Name.Contains("2") || t.Name.Contains("3") || t.Name.Contains("4") || t.Name.Contains("5") || t.Name.Contains("6") || t.Name.Contains("7") || t.Name.Contains("8") || t.Name.Contains("9"))
            {
                ModelState.AddModelError("Name", "Name can't contains number");
            }
           
       
            if (ModelState.IsValid)
            {
           
                if (t.Id == 0)
                {
                    if (t.ClientFile != null && t.ClientFile.Length > 0)
                    {
                       
                        using (MemoryStream stream = new MemoryStream())
                        {
                            t.ClientFile.CopyTo(stream);
                            t.Image = stream.ToArray();     
                        }
                    }
                    TempData["success"] = $"Category: {t.Name} Is Added";
                    _unit.categories.Addone(t);
                }
                else
                {
                    var category = _unit.categories.Find(t.Id);
                    if (t.ClientFile != null && t.ClientFile.Length > 0)
                    {
                       
                        using (MemoryStream stream = new MemoryStream())
                        {
                            t.ClientFile.CopyTo(stream);
                            category.Image = stream.ToArray(); 
                        }
                    }
                    category.Name=t.Name;
                    TempData["success"] = $"Category: {category.Name} Is Updated";
                    _unit.categories.UpdateOne(category);
                }

            
                return RedirectToAction("Index");

            }
            else
            {
          
                return View(t);
            }
        }

        public IActionResult Delete(int id)
        {
            
            var category = _unit.categories.Find(id);
            _unit.categories.DeleteOne(category);


            return RedirectToAction("Index");
        }
    }

}

eMart/Controllers/CategoryController.cs
using eMart.DTO_Models;
using eMart.Models;
using eMart.Repository.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;


namespace eMart.Controllers
{
    [AllowAnonymous]
    public class CategoryController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(ILogger<HomeController> logger, IUnitOfWork unit)
        {
            _logger = logger;
            _unitOfWork = unit;
        }
        public async Task<IActionResult> Index(int id, int pg = 1)
        {
            var category = await _unitOfWork.categories.FindAsync(id);
            if (category == null)
            {

                return NotFound();
            }
            ViewBag.isAdmin = HttpContext.Session.GetString("isAdmin");
            ViewData["Count"] = HttpContext.Session.GetInt32("count");
            ViewData["Title"] = category.Name;
            var categorysubCategories = _unitOfWork.subCategories.FindAll().Where(x => x.CategoryId == id);
   
            var products = _unitOfWork.products.FindAll(nameof(Product.Reviews),nameof(Product.brand)).Where(x => categorysubCategories.Any(c => c.Id == x.SubCategoryId));
            List<Brand> brands = new List<Brand>();
            foreach (var product in products)
            {
                brands.Add(product.brand);
                if (!product.Reviews.IsNullOrEmpty())
                {
                    var Rates = product.Reviews.Select(x => x.Rate);
                    product.Rate = Rates.Sum() / Rates.Count();
                }


            }
            
            
            ViewBag.Brands = brands.Select(b => b.Name).Distinct().ToList();
            ViewBag.Categories = categorysubCategories.Select(c => c.Name);

            ViewData["Id"] = id;
            const int pageSize = 10;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = products.Count();
            var Pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = products.Skip(recSkip).Take(Pager.PageSize).ToList();


            ViewBag.Pager = Pager;
            ViewBag.pgInCategory = Pager.CurrentPage;


            CategoryViewModel CVM = new CategoryViewModel
            {
                Products = new List<Product>(data),
                SubCategories = new List<SubCategory>(categorysubCategories)
            };
            return View(CVM);
        }
    }
}

eMart/Controllers/ProductController.cs
using eMart.DTO_Models;
using eMart.Models;
using eMart.Repository.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;

namespace eMart.Controllers
{
    [AllowAnonymous]
    public class ProductController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<AppUser> _user;   
        public ProductController(ILogger<HomeController> logger, IUnitOfWork unit,UserManager<AppUser> user)
        {
            _logger = logger;
            _unitOfWork = unit;
            _user = user;
        }
    
        public async Task<IActionResult> Index(int id)
        {
            ViewBag.isAdmin = HttpContext.Session.GetString("isAdmin");
            ViewData["Count"] = HttpContext.Session.GetInt32("count");

            var products = await _unitOfWork.products.FindAllAsync(nameof(Product.brand));
            var product = products.SingleOrDefault(x => x.Id == id);

            var reviews = await _unitOfWork.reviews.FindAllAsync(nameof(Review.User));
            reviews = reviews.Where(x => x.ProductId == id);

            var user = await _user.GetUserAsync(HttpContext.User);

            productDto productDto = new productDto(product, user);

            ViewData["Title"] = product.Name;
            if (!reviews.IsNullOrEmpty())
            {
                foreach (var review in reviews) 
                {
                    productDto.reviews.Add(review);
                }
            }



            return View(productDto);
        }

    }
}

eMart/Controllers/SubCategoryController.cs
using eMart.Models;
using eMart.Repository.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SendGrid.Helpers.Mail;

namespace eMart.Controllers
{
    [AllowAnonymous]
    public class SubCategoryController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public SubCategoryController(ILogger<HomeController> logger, IUnitOfWork unit)
        {
            _logger = logger;
            _unitOfWork = unit;
        }
        public async Task<IActionResult> Index(int id , int pg = 1)
        {
            var subcategory = await _unitOfWork.subCategories.FindAsync(id);
            if (subcategory == null)
            {

                return NotFound();
            }
            ViewBag.isAdmin = HttpContext.Session.GetString("isAdmin");
            ViewData["Count"] = HttpContext.Session.GetInt32("count");
            ViewData["Title"] = subcategory.Name;
            var products = _unitOfWork.products.FindAll(nameof(Product.Reviews),nameof(Product.brand));
            var subproducts = products.Where(x => x.SubCategoryId == id);
            List<Brand> brands = new List<Brand>();
            foreach (var product in subproducts)
            {
                brands.Add(product.brand);
                if (!product.Reviews.IsNullOrEmpty())
                {
                    var Rates = product.Reviews.Select(x => x.Rate);
                    product.Rate = Rates.Sum() / Rates.Count();
                }


            }
            List<string> subCategories = new List<string>();
            subCategories.Add(subcategory.Name);
            ViewBag.Brands = brands.Select(b => b.Name).Distinct().ToList();
            ViewBag.Categories = subCategories;

            ViewData["Id"] = id;
            const int pageSize = 10;
            if (pg < 1)
            {
                pg = 1;
            }
            int recsCount = subproducts.Count();
            var Pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = subproducts.Skip(recSkip).Take(Pager.PageSize).ToList();


            ViewBag.Pager = Pager;
            ViewBag.pgInSubCategory = Pager.CurrentPage;
            return View(data);
        }
    }
}

eMart/Views/Category/Index.cshtml
@model eMart.DTO_Models.CategoryViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@using eMart.DTO_Models
@inject IViewLocalizer localizer

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
    FilterData filterData = null;
}
<link href="~/css/cards.css" rel="stylesheet" />
<link rel="stylesheet" href="~/css/stars.css" />
<div class="container p-3">
    <partial name="_notify" />

    <div class="row">
        <!-- Filter Sidebar -->
        <div class="col-md-3">
            <partial name="_Filter" model="filterData" />
        </div>

        <!-- Main Content -->
        <div class="col-md-9">
            <!-- Subcategories Section -->
            <h2>@localizer["Subcategories"]</h2>
            <div class="row mb-4">
                @if (Model.SubCategories.Any())
                {
                    foreach (var m in Model.SubCategories)
                    {
                        <div class="col-md-4 mb-3">
                            <div class="card h-100">
                                <div class="card-img">
                                    <a asp-action="Index" asp-controller="SubCategory" asp-route-id="@m.Id">
                                        <img src="@m.ImgSrc" alt="@m.Name" class="img-fluid" />
                                    </a>
                                </div>
                                <div class="card-footer text-center">@m.Name</div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="col-12">
                        <p class="text-muted">@localizer["No subcategories available."]</p>
                    </div>
                }
            </div>

            <hr />

            <!-- Products Section -->
            <h2>@localizer["Products"]</h2>
            <partial name="_categoryPager" model="@pager" />
            <div class="row">
                @if (Model.Products.Any())
                {
                    foreach (var m in Model.Products)
                    {
                        <div class="col-md-4 mb-3">
                            <div class="card h-100">
                                <a asp-action="Index" asp-controller="Product" asp-route-id="@m.Id">
                                    <div class="card-img">
                                        <img src="@m.ImgSrc" alt="@m.Name" class="img-fluid" />
                                    </div>
                                </a>
                                <div class="card-footer text-center">
                                    <a asp-action="Index" asp-controller="Product" asp-route-id="@m.Id">
                                        <div>@m.Name</div>
                                    </a>
                                    <div class="star-rating">
                                        @for (int i = 1; i <= 5; i++)
                                        {
                                            if (i <= m.Rate)
                                            {
                                                <span class="star filled">★</span>
                                            }
                                            else
                                            {
                                                <span class="star">★</span>
                                            }
                                        }
                                    </div>
                                    <div>@m.price.ToString("c")</div>
                                    @if (m.Stock == 0)
                                    {
                                        <div class="btn btn-warning disabled">@localizer["Out of Stock"]</div>
                                    }
                                    else
                                    {
                                        <a asp-action="AddToCart" asp-controller="Cart" asp-route-catpg="@pageNo" asp-route-id="@m.Id" asp-route-returnUrl="@string.Format("{0}", Context.Request.Path)" class="btn btn-success">
                                            <i class="bi bi-plus-square"></i> @localizer["Add to Cart"]
                                        </a>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="col-12 text-center">
                        <p>@localizer["No products available in this category."]</p>
                    </div>
                }
            </div>
            <partial name="_categoryPager" model="@pager" />
        </div>
    </div>
</div>